![lop](../../images/logo_diive1_128px.png)

<span style='font-size:32px; display:block;'>
<b>
    Read single EddyPro _fluxnet_ output file with DataFileReader
</b>
</span>

---
**Notebook version**: `1` (20 Apr 2024)  
**Author**: Lukas HÃ¶rtnagl (holukas@ethz.ch)

</br>

# Description

This example shows how to read the `EddyPro` `_fluxnet_` output file with `DataFileReader` by manually providing parameters.

# Imports

In [1]:
import importlib.metadata
import warnings
from datetime import datetime

warnings.filterwarnings('ignore')
from diive.core.io.filereader import DataFileReader

version_diive = importlib.metadata.version("diive")
print(f"diive version: v{version_diive}")

diive version: v0.85.0

## Using `DataFileReader` with parameters

In [2]:
FILE = r"..\..\diive\configs\exampledata\EDDYPRO-FLUXNET-CSV-30MIN_multiple\eddypro_CH-HON_FR-20240819-090003_fluxnet_2024-08-19T090019_adv.csv"
dfr = DataFileReader(filepath=FILE,
                     data_header_section_rows=[0],  # Header section (before data) comprises 1 row
                     data_skip_rows=[],  # Skip no rows
                     data_header_rows=[0],
                     # Header with variable names and units, in this case only variable names in first row of header                     
                     data_varnames_row=0,  # Variable names are in first row of header
                     data_varunits_row=None,  # Header does not contain any variable units
                     data_na_vals=[-9999],
                     # List of values interpreted as missing values, EddyPro uses -9999 for missing values in ouput file                     
                     data_freq="30min",  # Time resolution of the data is 30-minutes
                     data_delimiter=",",  # This csv file uses the comma as delimiter
                     data_nrows=None,
                     # How many data rows to read from files, mainly used for testing, in this case None to read all rows in file
                     timestamp_idx_col=["TIMESTAMP_END"],  # Name of the column that is used for the timestamp index
                     timestamp_datetime_format="%Y%m%d%H%M",  # Timestamp in the files looks like this: 202107010300
                     timestamp_start_middle_end="end",
                     # Timestamp in the file defined in *timestamp_idx_col* refers to the END of the averaging interval
                     output_middle_timestamp=True,
                     # Timestamp in output dataframe (after reading the file) refers to the MIDDLE of the averaging interval
                     compression=None)  # File is not compressed (not zipped)

In [3]:
df, meta = dfr.get_data()

File data are now stored in a dataframe:

In [4]:
df

                     TIMESTAMP_START  DOY_START   DOY_END  FILENAME_HF  SW_IN_POT  NIGHT  EXPECT_NR  FILE_NR  CUSTOM_FILTER_NR  WD_FILTER_NR  SONIC_NR  T_SONIC_NR   CO2_NR   H2O_NR  CH4_NR  ...  BADM_INST_GA_CP_TUBE_LENGTH_GA_NONE  BADM_INST_GA_CP_TUBE_IN_DIAM_GA_NONE  BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_NONE  HPATH_GA_NONE  VPATH_GA_NONE  RESPONSE_TIME_GA_NONE  NUM_CUSTOM_VARS  CUSTOM_DATA_SIZE_IRGA75_MEAN  CUSTOM_STATUS_CODE_IRGA75_MEAN  CUSTOM_GA_DIAG_CODE_IRGA75_MEAN  CUSTOM_AGC_MEAN  CUSTOM_FAST_T_MEAN  CUSTOM_AIR_P_MEAN  CUSTOM_COOLER_V_MEAN  NUM_BIOMET_VARS
TIMESTAMP_MIDDLE                                                                                                                                                                              ...
2024-08-16 01:15:00     202408160100   229.0416  229.0624          NaN      0.000      1      36000    36000             36000         36000     36000       36000  36000.0  36000.0     NaN  ...                                  NaN                                   NaN                                     NaN            NaN            NaN                    NaN                7                          16.0                             0.0                          250.000          62.5000             20.2846            95999.6               1.36480                0
2024-08-16 01:45:00     202408160130   229.0624  229.0833          NaN      0.000      1      36000    36000             36000         36000     36000       36000  36000.0  36000.0     NaN  ...                                  NaN                                   NaN                                     NaN            NaN            NaN                    NaN                7                          16.0                             0.0                          250.000          62.5000             20.1841            95999.7               1.36725                0
2024-08-16 02:15:00     202408160200   229.0833  229.1041          NaN      0.000      1      36000    36000             36000         36000     36000       36000  36000.0  36000.0     NaN  ...                                  NaN                                   NaN                                     NaN            NaN            NaN                    NaN                7                          16.0                             0.0                          250.000          62.5000             19.9790            95999.6               1.35754                0
2024-08-16 02:45:00     202408160230   229.1041  229.1249          NaN      0.000      1      36000    36000             36000         36000     36000       36000  36000.0  36000.0     NaN  ...                                  NaN                                   NaN                                     NaN            NaN            NaN                    NaN                7                          16.0                             0.0                          250.000          62.5000             19.8198            96000.2               1.35498                0
2024-08-16 03:15:00     202408160300   229.1249  229.1458          NaN      0.000      1      36000    36000             36000         36000     36000       36000  36000.0  36000.0     NaN  ...                                  NaN                                   NaN                                     NaN            NaN            NaN                    NaN                7                          16.0                             0.0                          250.000          62.5000             19.7793            95999.8               1.35391                0
...                              ...        ...       ...          ...        ...    ...        ...      ...               ...           ...       ...         ...      ...      ...     ...  ...                                  ...                                   ...                                     ...            ...            ...                    ...              ...                           ...                             ...                              ...              ...                 ...                ...                   ...              ...
2024-08-18 16:45:00     202408181630   231.6873  231.7082          NaN    560.965      0      36000    36000             36000         36000     36000       36000  35962.0  36000.0     NaN  ...                                  NaN                                   NaN                                     NaN            NaN            NaN                    NaN                7                          16.0                             0.0                          250.970          68.5627             20.8094            95411.7               1.31573                0
2024-08-18 17:15:00     202408181700   231.7082  231.7290          NaN    451.566      0      36000    36000             36000         36000     36000       36000  36000.0      NaN     NaN  ...                                  NaN                                   NaN                                     NaN            NaN            NaN                    NaN                7                          16.0                             0.0                          253.112          81.9497             21.0953            95416.2               1.31731                0
2024-08-18 17:45:00     202408181730   231.7290  231.7498          NaN    338.255      0      36000    36000             36000         36000     36000       36000  35971.0      NaN     NaN  ...                                  NaN                                   NaN                                     NaN            NaN            NaN                    NaN                7                          16.0                             0.0                          253.769          86.0561             20.7517            95418.3               1.31258                0
2024-08-18 18:15:00     202408181800   231.7498  231.7707          NaN    222.973      0      36000    36000             36000         36000     36000       36000  35207.0      NaN     NaN  ...                                  NaN                                   NaN                                     NaN            NaN            NaN                    NaN                7                          16.0                             0.0                          251.246          70.2892             19.8784            95466.6               1.30427                0
2024-08-18 18:45:00     202408181830   231.7707  231.7915          NaN    107.690      0      36000    36000             36000         36000     36000       36000      NaN      NaN     NaN  ...                                  NaN                                   NaN                                     NaN            NaN            NaN                    NaN                7                          16.0                             0.0                          253.685          85.5325             18.8494            95500.3               1.29177                0

[132 rows x 480 columns]

Metadata are also stored, which inlcudes units (if available in the data files) and tags (for later processing). In this example, the column `TIMESTAMP_END` was used to parse the timestamp index, and was thus removed from the data columns to avoid having identical names for index and data column. However, the original data column still shows up in the metadata.

In [5]:
meta

                           UNITS     TAGS                       ADDED VARINDEX
TIMESTAMP_START       -no-units-  [#orig]  2025-01-25 01:47:09.962974        0
TIMESTAMP_END                NaN      NaN                         NaN      NaN
DOY_START             -no-units-  [#orig]  2025-01-25 01:47:09.962974        1
DOY_END               -no-units-  [#orig]  2025-01-25 01:47:09.962974        2
FILENAME_HF           -no-units-  [#orig]  2025-01-25 01:47:09.962974        3
...                          ...      ...                         ...      ...
CUSTOM_AGC_MEAN       -no-units-  [#orig]  2025-01-25 01:47:09.962974      475
CUSTOM_FAST_T_MEAN    -no-units-  [#orig]  2025-01-25 01:47:09.962974      476
CUSTOM_AIR_P_MEAN     -no-units-  [#orig]  2025-01-25 01:47:09.962974      477
CUSTOM_COOLER_V_MEAN  -no-units-  [#orig]  2025-01-25 01:47:09.962974      478
NUM_BIOMET_VARS       -no-units-  [#orig]  2025-01-25 01:47:09.962974      479

[481 rows x 4 columns]

# End of notebook

In [6]:
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished {dt_string}")

Finished 2025-01-25 01:47:17